version: "3"
services:
  ifly-http:
    build: .
    volumes:
      - ./index.js:/data/app/index.js
    ports:
      - "9000:9000"
    command: ./node_modules/nodemon/bin/nodemon.js index.js --appId xxx
